# Generated by Django 2.0.5 on 2018-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledu_test', '0002_auto_20180524_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
